### ISSUE TITLE
[BUG] Duplicated Machine?

### ISSUE THREAD

**Issue by iceBear67** [InlinedLambdas/AstralFlow#119]
```
[21:05:00 WARN]: java.lang.IllegalStateException: Error while calling hook (type: Chunk Load )
[21:05:00 WARN]: 	at AstralFlow-0.0.1-all.jar//io.ib67.astralflow.AstralFlow.callHooks(AstralFlow.java:352)
[21:05:00 WARN]: 	at AstralFlow-0.0.1-all.jar//io.ib67.astralflow.internal.listener.WorldListener.onChunkLoad(WorldListener.java:42)
[21:05:00 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor69.execute(Unknown Source)
[21:05:00 WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:05:00 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:05:00 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:05:00 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[21:05:00 WARN]: 	at net.minecraft.world.level.chunk.Chunk.loadCallback(Chunk.java:809)
[21:05:00 WARN]: 	at net.minecraft.server.level.PlayerChunk.lambda$updateFutures$20(PlayerChunk.java:679)
[21:05:00 WARN]: 	at net.minecraft.server.level.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:195)
[21:05:00 WARN]: 	at net.minecraft.server.level.ChunkProviderServer$b.y(ChunkProviderServer.java:1264)
[21:05:00 WARN]: 	at net.minecraft.server.level.ChunkProviderServer.d(ChunkProviderServer.java:831)
[21:05:00 WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1401)
[21:05:00 WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[21:05:00 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[21:05:00 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1462)
[21:05:00 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[21:05:00 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[21:05:00 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[21:05:00 WARN]: Caused by: java.lang.IllegalStateException: Failed to setup machine class io.ib67.astralflow.machines.JebWool (t: class io.ib67.astralflow.machines.JebWool, s:io.ib67.astralflow.machines.JebWool@146191d5 )
[21:05:00 WARN]: 	at AstralFlow-0.0.1-all.jar//io.ib67.astralflow.manager.IMachineManager.setupMachine(IMachineManager.java:51)
[21:05:00 WARN]: 	at AstralFlow-0.0.1-all.jar//io.ib67.astralflow.manager.impl.MachineManagerImpl.initChunk(MachineManagerImpl.java:75)
[21:05:00 WARN]: 	at AstralFlow-0.0.1-all.jar//io.ib67.astralflow.AstralFlow.callHooks(AstralFlow.java:350)
[21:05:00 WARN]: 	... 18 more
[21:05:00 WARN]: Caused by: java.lang.IllegalStateException: Machine io.ib67.astralflow.machines.JebWool@146191d5 is already active
[21:05:00 WARN]: 	at AstralFlow-0.0.1-all.jar//io.ib67.astralflow.manager.impl.MachineManagerImpl.activateMachine(MachineManagerImpl.java:124)
[21:05:00 WARN]: 	at AstralFlow-0.0.1-all.jar//io.ib67.astralflow.manager.IMachineManager.setupMachine(IMachineManager.java:47)
[21:05:00 WARN]: 	... 20 more
```

**Comment by iceBear67** [comment]
This is related to Pushable, i.e #98
